services:
  postgres:
    image: postgres:16-alpine
    env:
      POSTGRES_DB: jobspipeline
      POSTGRES_USER: jobadmin
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    options: >-
      --health-cmd="pg_isready -U jobadmin -d jobspipeline"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=5

  # Add other services as needed
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
